<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>error_Message</name>
   <tag></tag>
   <elementGuidId>bd9c90ef-03a0-464c-84d6-50a1ee6fcff6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;login_button_container&quot;]/div/form/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//*[@id=&quot;login_button_container&quot;]/div/form/h3/text()[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
